### ISSUE TITLE
Add me to your webring plz

### ISSUE THREAD

**Issue by amtunlimited** [miketaylr/miketaylr.com-blog#11]
aarontag.dev/blog

**Comment by miketaylr** [comment]
Of course! I totally missed this. :)~

**Comment by miketaylr** [comment]
![Screen Shot 2021-03-03 at 5 07 38 PM](https://user-images.githubusercontent.com/67283/109884708-04cb0880-7c43-11eb-9072-8afc5cf8a0e9.png)

**Comment by amtunlimited** [comment]
<3
